server:
  port: 8081

spring:
  application:
    name: DocumentVerification

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/document_verification_db
    username: postgres
    password: 8990

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

frontend:
  base-url: http://localhost:3000
