spring:
  application:
    name: DocumentVerification

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/document_verification_db
    username: raidenz
    password: qwer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

frontend:
  base-url: http://localhost:3000

